name: Deploy to Server

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            # ÐµÑÐ»Ð¸ Ð¿ÐµÑ€Ð²Ñ‹Ð¹ Ñ€Ð°Ð· â€” ÐºÐ»Ð¾Ð½Ð¸Ñ€ÑƒÐµÐ¼
            if [ ! -d "/home/hfam/engine/.git" ]; then
              git clone git@github.com:suntouse2/hfam.git /home/hfam
            fi

            cd /home/hfam

            echo "ðŸ“¥ ÐžÐ±Ð½Ð¾Ð²Ð»ÑÐµÐ¼ ÐºÐ¾Ð´"
            git reset --hard
            git pull origin master

            echo "ðŸ“¦ Ð¡Ð¾Ð±Ð¸Ñ€Ð°ÐµÐ¼ engine"
            cd packages/engine
            npm ci
            npm run build
            pm2 restart engine || pm2 start npm --name "engine" -- run start

            echo "ðŸ¤– Ð¡Ð¾Ð±Ð¸Ñ€Ð°ÐµÐ¼ telegram-bot"
            cd packages/telegram-bot
            npm ci
            npm run build
            pm2 restart telegram-bot || pm2 start npm --name "telegram-bot" -- run start

            echo "âœ… Deploy completed!"
          EOF
